blank_issues_enabled: false
contact_links:
  - name: Helper-Scripts Community Support
    url: https://github.com/community-scripts/ProxmoxVE/discussions
    about: Please ask and answer questions here.
