blank_issues_enabled: false
contact_links:
    - name: ðŸ¤” Questions and Help
      url: https://github.com/community-scripts/ProxmoxVE/discussions
      about: For suggestions or questions, please use the Discussions section.
    - name: ðŸŒŸ Feature request
      url: https://github.com/community-scripts/ProxmoxVE/discussions/new?category=request-script
      about: For feature/script requests, please use the Discussions section.
    - name: ðŸ’» Discord
      url: https://discord.gg/UHrpNWGwkH
      about: Join our Discord server to chat with other users in the Proxmox Helper Scripts community.
